/**
 * Core game constants
 */

export const TILE_SIZE = 16;
export const MAP_W = 60;
export const MAP_H = 40;

export const MODEL_NAME = "gemini-2.5-flash-lite";

// Game states
export const GAME_STATES = {
  LOGO: 'LOGO',
  INTRO: 'INTRO',
  STORY: 'STORY',
  TITLE: 'TITLE',
  HOWTO: 'HOWTO',
  SELECT: 'SELECT',
  PLAY: 'PLAY',
  DIALOG: 'DIALOG',
  VISITOR_SPLASH: 'VISITOR_SPLASH',
  BOSS_INTRO: 'BOSS_INTRO',
  BOSS: 'BOSS',
  YARD_INTRO: 'YARD_INTRO',
  YARD_LEVEL: 'YARD_LEVEL',
  BEZOS_INTRO: 'BEZOS_INTRO',
  BEZOS_BOSS: 'BEZOS_BOSS',
  MECHA_BOSS_INTRO: 'MECHA_BOSS_INTRO',
  MECHA_BOSS: 'MECHA_BOSS',
  MECHA_SIMON_SPLASH: 'MECHA_SIMON_SPLASH',
  THRONE_CONFRONTATION: 'THRONE_CONFRONTATION',
  MECHA_TRANSFORM: 'MECHA_TRANSFORM',
  SIMON_MECHA_TRANSFORM: 'SIMON_MECHA_TRANSFORM',
  BEZOS_ESCAPE: 'BEZOS_ESCAPE',
  CREDITS: 'CREDITS',
  WIN_SPLASH: 'WIN_SPLASH',
  LOSE_SPLASH: 'LOSE_SPLASH',
  GAMEOVER_SPLASH: 'GAMEOVER_SPLASH',
  GAMEOVER: 'GAMEOVER',
  WIN: 'WIN',
  BEZOS_WIN: 'BEZOS_WIN'
};
